language: node_js
cache:
  directories:
  - "~/.npm"
  - "./node_modules/"
notifications:
  email: false
node_js:
- '10'
jobs:
  include:
    - stage: test
      script:
        - npm run test
        - npm run build
    - stage: deploy
      script:
        - git fetch --all --tags
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run release --access public; fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
