language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '11'
- '8'
jobs:
  include:
    - stage: test
      script:
        - npm run test
        - npm run build
    - stage: deploy
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run release; fi
after_success:
# - npm run travis-deploy-once "npm run report-coverage"
# - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
#   run travis-deploy-once "npm run deploy-docs"; fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
